### ISSUE TITLE
Enable GH Pages & Initial `gh-pages` branch

### ISSUE THREAD

**Issue by coatless** [AAGI-AUS/AAGIQuarto#2]
As I forked the repo, the underlying publish action to show a demo slide deck needs to be enabled on the main repo. Some quick steps: 

Enable `gh-pages` branch via typing into the quarto project's console: 

```sh
quarto publish gh-pages
```

Then, on the GitHub repo: 

<img width="1463" alt="Enable GitHub Pages on the repository" src="https://github.com/user-attachments/assets/79400c99-18fc-4515-b5e4-bda2da84d306">

Resolves: 

https://github.com/AAGI-Org-AU-Public/AAGIRevealjs/actions/runs/10069073518/job/27835478295#step:6:42

**Comment by adamhsparks** [comment]
all done, thanks, @coatless!
